### ISSUE TITLE
uri rewrite

### ISSUE THREAD

**Issue by roland-x83** [bitnami/bitnami-docker-codeigniter#79]
Hi 

I've got a problem with rewrite uri in my environmet. 
I.e url like https:/example.com/account_password_reset/roland/x844/7ac284b31d89efae02acdcbe2f8e234d

doesn't work. Seems like tiny server rewrite url on his own way, and Im not able to use my .htaccess rules.

**Comment by andresbono** [comment]
Hi @roland-x83, htaccess files are not read by this container. If you check the process serving the requests you will see that it's PHP itself instead of Apache. For that reason, if you want to implement a redirection/rewrite, you may want to use an additional container acting as proxy.

Please note that this is a development container. That's the reason why php is serving the requests instead of Apache or Nginx.
